language: python
python: 3.6

install: "pip install tox"
script: "tox -e $TRAVIS_BUILD"

matrix:
  include:
    - env: TRAVIS_BUILD=py36
    - env: TRAVIS_BUILD=lint
  allow_failures:
    - env: TRAVIS_BUILD=lint
